config/routes.rb
Rails.application.routes.draw do
  scope :portfolio_2 do
    root 'home#top'
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
    }
    devise_scope :user do
      get 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    end
    resources :categories
    resources :contents
    resources :posts
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  belongs_to :category
  has_many :posts, dependent: :destroy

  validates :user_id, presence: true
  validates :genre_id, presence: true
  validates :category_id, presence: true
  validates :title, presence: true, length: { in: 1..20 }
  validates :author, presence: true

  def self.search(search)
    if search
      Content.joins(:category).where(['title LIKE ? OR author LIKE ? OR name LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"])
    else
      Content.all
    end
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :move_to_signed_in
  before_action :set_content, only: %i(edit update destroy)
  before_action :side_bar, only: %i(index new edit)

  # GET /contents or /contents.json
  def index
    @contents = Content.search(params[:search]).where(user_id: current_user.id).order(updated_at: :desc)
  end

  # GET /contents/new
  def new
    @content = Content.new
    @genre = Genre.find(params[:genre_id])
    @categories = Category.where(user_id: current_user.id, genre_id: @genre.id)
  end

  # GET /contents/1/edit
  def edit
    @genre = Genre.find(params[:genre_id])
    @categories = Category.where(genre_id: @genre.id)
  end

  # POST /contents or /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to contents_url(@content), notice: "コンテンツを登録しました" }
        format.json { render :index, status: :created, location: @content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1 or /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to contents_url(@content), notice: "コンテンツを更新しました" }
        format.json { render :index, status: :ok, location: @content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1 or /contents/1.json
  def destroy
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url, notice: "コンテンツを削除しました" }
      format.json { head :no_content }
    end
  end

  private

  def move_to_signed_in
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_content
    @content = Content.find(params[:id])
  end

  def side_bar
    @genres = Genre.all
    @category = Category.all
  end

  # Only allow a list of trusted parameters through.
  def content_params
    params.require(:content).permit(:user_id, :genre_id, :category_id, :title, :author)
  end
end

app/views/contents/_content.html.erb
<div id="<%= dom_id content %>">
  <div class="index_box">
    <p>
      <strong>ジャンル：</strong>
      <span class="next_colon"><%= content.genre.name %></span>
    </p>
    <p>
      <strong>カテゴリ名：</strong>
      <span class="next_colon"><%= content.category.name %></span>
    </p>
    <p>
      <strong>作品名：</strong>
      <span class="next_colon"><%= content.title %></span>
    </p>
    <p>
      <% if (content.genre_id === 1) %>
        <strong>著者名：</strong>
      <% elsif (content.genre_id === 2) %>
        <strong>作者名：</strong>
      <% elsif (content.genre_id === 3) %>
        <strong>監督名・出演者名など：</strong>
      <% else %>
        <strong>アーティスト名：</strong>
      <% end %>
      <span class="next_colon"><%= content.author %></span>
    </p>
    <div class="links">
      <%= link_to "日記を書く", new_post_path(content_id: content.id, content_title: content.title, category_id: content.category_id) %>
      <%= link_to "編集", edit_content_path(content, genre_id: content.genre_id, category_id: content.category.id) %>
      <%= button_to "削除", content, method: :delete %>
    </div>
  </div>
</div>

app/views/contents/_form.html.erb
<%= form_with(model: content) do |form| %>
  <% if content.errors.any? %>
    <div class="alert">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>
      <ul>
        <% content.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.hidden_field :genre_id, value: @genre.id %>
  <div class="form_field">
    <%= form.label :category_id, "カテゴリ：", style: "display: block" %>
    <span class="next_colon">
      <% if (controller.action_name == 'new') %>
        <% if (@genre.id === 1) %>
          <%= form.select :category_id, @categories.map{ |category| [category.name, category.id] }, include_blank: "選択して下さい" %>
        <% elsif (@genre.id === 2) %>
          <%= form.select :category_id, @categories.map{ |category| [category.name, category.id] }, include_blank: "選択して下さい" %>
        <% elsif (@genre.id === 3) %>
          <%= form.select :category_id, @categories.map{ |category| [category.name, category.id] }, include_blank: "選択して下さい" %>
        <% else %>
          <%= form.select :category_id, @categories.map{ |category| [category.name, category.id] }, include_blank: "選択して下さい" %>
        <% end %>
      <% else %>
        <%= content.category.name %>
      <% end %>
    </span>
  </div><br/>
  <div class="form_box">
    <div class="form_field">
      <%= form.label :title, "作品名：", style: "display: block" %>
      <span class="next_colon">
        <%= form.text_field :title %>
      </span>
    </div>
    <div class="form_field">
      <% if (@genre.id === 1) %>
        <%= form.label :author, "著者名：", style: "display: block" %>
      <% elsif (@genre.id === 2) %>
        <%= form.label :author, "作者名：", style: "display: block" %>
      <% elsif (@genre.id === 3) %>
        <%= form.label :author, "監督名・出演者名：", style: "display: block" %>
      <% else %>
        <%= form.label :author, "アーティスト名：", style: "display: block" %>
      <% end %>
      <span class="next_colon">
        <%= form.text_field :author %>
      </span>
    </div>
    <div>
      <% if (controller.action_name == 'new') %>
        <%= form.submit "登録", class: "actions_btn" %>
      <% else %>
        <%= form.submit "更新", class: "actions_btn" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/contents/edit.html.erb
<div class="top_page">
  <%= render 'home/side_bar' %>
  <div class="main_content">
    <div class="content_title">
      <h3>編集 - <%= @content.title %> -</h3>
    </div>
    <div class="back">
      <%= link_to "一覧に戻る", contents_path %>
    </div>
    <div class="new_form">
      <%= render "form", content: @content %>
    </div>
  </div>
</div>

app/views/contents/index.html.erb
<div class="top_page">
  <%= render 'home/side_bar' %>
  <div class="main_content" %>
    <p class="notice"><%= notice %></p>
    <div class="content_title">
      <h3>コンテンツ一覧</h3>
      <div class="responsive">
        <%= link_to "NOVEL 登録", new_content_path(genre_id: 1), class: "new_btn" %>
      </div>
      <div class="responsive">
        <%= link_to "COMIC 登録", new_content_path(genre_id: 2), class: "new_btn" %>
      </div>
      <div class="responsive">
        <%= link_to "MOVIE 登録", new_content_path(genre_id: 3), class: "new_btn" %>
      </div>
      <div class="responsive">
        <%= link_to "MUSIC 登録", new_content_path(genre_id: 4), class: "new_btn" %>
      </div>
    </div>
    <div id="contents" class="content_box">
      <% @contents.each do |content| %>
        <%= render content %>
      <% end %>
    </div>
  </div>
</div>

app/views/contents/new.html.erb
<div class="top_page">
  <%= render 'home/side_bar' %>
  <div class="main_content">
    <div class="content_title">
      <h3>新規登録</h3>
    </div>
    <div class="back">
      <%= link_to "一覧に戻る", contents_path %>
    </div>
    <div class="new_form">
      <%= render "form", content: @content %>
    </div>
  </div>
</div>