config/routes.rb
Rails.application.routes.draw do
  scope :portfolio_2 do
    root 'home#top'
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
    }
    devise_scope :user do
      get 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    end
    resources :categories
    resources :contents
    resources :posts
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :move_to_signed_in

  def top
    @genres = Genre.all
    @categories = Category.where(user_id: current_user.id)
    @contents = Content.where(user_id: current_user.id).order(updated_at: :desc).limit(3)
    @posts = Post.where(user_id: current_user.id).order(updated_at: :desc).limit(3)
  end

  private

  def move_to_signed_in
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end
end

app/views/home/_side_bar.html.erb
<div class="side_bar">
  <div class="search">
    <div class="search_field">
      <%= form_tag categories_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search], placeholder: "カテゴリを探す..." %>
        <%= submit_tag '検索', :name => nil %>
      <% end %>
    </div>
    <div class="search_field">
      <%= form_tag contents_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search], placeholder: "作品を探す..." %>
        <%= submit_tag '検索', :name => nil %>
      <% end %>
    </div>
    <div class="search_field">
      <%= form_tag posts_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search], placeholder: "日記を探す..." %>
        <%= submit_tag '検索', :name => nil %>
      <% end %>
    </div>
  </div>
  <% @genres.each do |genre| %>
    <details>
      <summary><div class="genre_name"><%= genre.name %></div></summary>
      <ui>
        <% genre.categories.each do |category| %>
          <% if user_signed_in? && category.user_id === current_user.id %>
            <details>
              <summary>
                <li class="category_name"><%= category.name %><span>(<%= category.posts.count %>)</span></li>
              </summary>
              <ul>
                <% category.contents.each do |content| %>
                  <%= link_to contents_path({ search: content.title}) do %>
                    <li class="content_name"><%= content.title %><span>(<%= content.posts.count %>)</span></li>
                  <% end %>
                <% end %>
              </ul>
            </details>
          <% end %>
        <% end %>
      </ul>
    </details>
  <% end %>
</div>

app/views/home/top.html.erb
<div class="top_page">
  <%= render 'home/side_bar' %>
  <div class="main_content">
    <p class="notice"><%= notice %></p>
    <div class="content_box">
      <h3>最近登録したコンテンツ</h3>
      <% @contents.each do |content| %>
        <div class="index_box">
          <p>作成日：<%= content.created_at.strftime('%Y年 %m月 %d日') %></p>
          <p>作品タイトル：<%= content.title %></p>
          <div class="links">
            <%= link_to "編集", edit_content_path(content, genre_id: content.genre_id, category_id: content.category.id) %>
            <%= button_to "削除", content, method: :delete %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="content_box">
      <h3>最近投稿した日記</h3>
      <% @posts.each do |post| %>
        <div class="index_box">
          <p>投稿日：<%= post.created_at.strftime('%Y年 %m月 %d日') %></p>
          <p>サブタイトル：<%= post.subtitle %></p>
          <p>日記：<%= post.diary %></p>
          <div class="links">
            <%= link_to "詳細", post_path(post) %>
            <%= link_to "編集", edit_post_path(post, category_id: post.category.id, content_id: post.content.id, content_title: post.content.title) %>
            <%= button_to "削除", post, method: :delete %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>